//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;


    // <summary>
    //   A strongly-typed resource class, for looking up localized strings, etc.
    // </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource()
        {
        }

        // <summary>
        //   Returns the cached ResourceManager instance used by this class.
        // </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        // <summary>
        //   Overrides the current thread's CurrentUICulture property for all
        //   resource lookups using this strongly typed resource class.
        // </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        // <summary>
        //   Looks up a localized string similar to About Us.
        // </summary>
        public static string About_Us
        {
            get
            {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to add file.
        // </summary>
        public static string add_file
        {
            get
            {
                return ResourceManager.GetString("add file", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to All Clients.
        // </summary>
        public static string All_Clients
        {
            get
            {
                return ResourceManager.GetString("All Clients", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to all packages.
        // </summary>
        public static string all_packages
        {
            get
            {
                return ResourceManager.GetString("all packages", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to All Products.
        // </summary>
        public static string all_products
        {
            get
            {
                return ResourceManager.GetString("all products", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to all Tools.
        // </summary>
        public static string all_Tools
        {
            get
            {
                return ResourceManager.GetString("all Tools", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to 6 To 11 (Y).
        // </summary>
        public static string Between_Six_To_Eleven_Years
        {
            get
            {
                return ResourceManager.GetString("Between Six To Eleven Years", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to 2 To 5 (Y).
        // </summary>
        public static string Between_Two_To_Five_Years
        {
            get
            {
                return ResourceManager.GetString("Between Two To Five Years", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Blogs.
        // </summary>
        public static string Blogs
        {
            get
            {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Careers.
        // </summary>
        public static string Careers
        {
            get
            {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Categories.
        // </summary>
        public static string Categories
        {
            get
            {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Clients.
        // </summary>
        public static string Clients
        {
            get
            {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Close.
        // </summary>
        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to company.
        // </summary>
        public static string company
        {
            get
            {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to contact.
        // </summary>
        public static string contact
        {
            get
            {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to contact information.
        // </summary>
        public static string contact_information
        {
            get
            {
                return ResourceManager.GetString("contact information", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Contact Us.
        // </summary>
        public static string Contact_Us
        {
            get
            {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Please feel free to contact us, using the toll-free number below or fill out the form and we will get back to you shortly..
        // </summary>
        public static string ContactBrief
        {
            get
            {
                return ResourceManager.GetString("ContactBrief", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to All copyrights reserved to.
        // </summary>
        public static string copyrights
        {
            get
            {
                return ResourceManager.GetString("copyrights", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to WHAT CUSTOMERS SAY ABOUT US.
        // </summary>
        public static string CustomerReview
        {
            get
            {
                return ResourceManager.GetString("CustomerReview", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Design &amp;  Developed by.
        // </summary>
        public static string Design
        {
            get
            {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to details.
        // </summary>
        public static string details
        {
            get
            {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Download.
        // </summary>
        public static string Download
        {
            get
            {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Download Center.
        // </summary>
        public static string Download_Center
        {
            get
            {
                return ResourceManager.GetString("Download Center", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Downloads.
        // </summary>
        public static string Downloads
        {
            get
            {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Email.
        // </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Email is required.
        // </summary>
        public static string EmailError
        {
            get
            {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Enter your email.
        // </summary>
        public static string Enter_your_email
        {
            get
            {
                return ResourceManager.GetString("Enter your email", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Enter your search.
        // </summary>
        public static string Enter_your_search
        {
            get
            {
                return ResourceManager.GetString("Enter your search", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to FAQs.
        // </summary>
        public static string FAQs
        {
            get
            {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Upload accepted file type please ex: (txt,doc,pdf,zip,rar,docx,xls,xlsx,ppt,pptx,csv).
        // </summary>
        public static string FileValidation
        {
            get
            {
                return ResourceManager.GetString("FileValidation", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to follow us.
        // </summary>
        public static string follow_us
        {
            get
            {
                return ResourceManager.GetString("follow us", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Full Name.
        // </summary>
        public static string Full_Name
        {
            get
            {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Full Name is required.
        // </summary>
        public static string FullName
        {
            get
            {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to get in.
        // </summary>
        public static string get_in
        {
            get
            {
                return ResourceManager.GetString("get in", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to home.
        // </summary>
        public static string home
        {
            get
            {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Home Page.
        // </summary>
        public static string Home_Page
        {
            get
            {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Invalid login attempt..
        // </summary>
        public static string Invalid_login_attempt_
        {
            get
            {
                return ResourceManager.GetString("Invalid login attempt.", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Name is required.
        // </summary>
        public static string JobNameError
        {
            get
            {
                return ResourceManager.GetString("JobNameError", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Choose Job.
        // </summary>
        public static string JobOpportunityError
        {
            get
            {
                return ResourceManager.GetString("JobOpportunityError", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to join now.
        // </summary>
        public static string join_now
        {
            get
            {
                return ResourceManager.GetString("join now", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to latest downloads.
        // </summary>
        public static string latest_downloads
        {
            get
            {
                return ResourceManager.GetString("latest downloads", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to latest News.
        // </summary>
        public static string latest_News
        {
            get
            {
                return ResourceManager.GetString("latest News", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to latest works.
        // </summary>
        public static string latest_works
        {
            get
            {
                return ResourceManager.GetString("latest works", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to This field minimum length of &apos;3&apos;..
        // </summary>
        public static string LengthError
        {
            get
            {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Media center.
        // </summary>
        public static string Media_center
        {
            get
            {
                return ResourceManager.GetString("Media center", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Tools.
        // </summary>
        public static string MenuTool
        {
            get
            {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Message.
        // </summary>
        public static string Message
        {
            get
            {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Please Enter a message.
        // </summary>
        public static string MessageError
        {
            get
            {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Mobile Number.
        // </summary>
        public static string Mobile_Number
        {
            get
            {
                return ResourceManager.GetString("Mobile Number", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to More Info.
        // </summary>
        public static string More_Info
        {
            get
            {
                return ResourceManager.GetString("More Info", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to News &amp; Events.
        // </summary>
        public static string News___Events
        {
            get
            {
                return ResourceManager.GetString("News & Events", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to newsletter.
        // </summary>
        public static string newsletter
        {
            get
            {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No Clients.
        // </summary>
        public static string No_Clients
        {
            get
            {
                return ResourceManager.GetString("No Clients", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No downloads available.
        // </summary>
        public static string No_downloads
        {
            get
            {
                return ResourceManager.GetString("No downloads", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No News Available.
        // </summary>
        public static string No_News
        {
            get
            {
                return ResourceManager.GetString("No News", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No Packages.
        // </summary>
        public static string No_Packages
        {
            get
            {
                return ResourceManager.GetString("No Packages", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No Products.
        // </summary>
        public static string No_Products
        {
            get
            {
                return ResourceManager.GetString("No Products", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No services available.
        // </summary>
        public static string No_services
        {
            get
            {
                return ResourceManager.GetString("No services", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No Tools.
        // </summary>
        public static string No_Tools
        {
            get
            {
                return ResourceManager.GetString("No Tools", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No Videos Available.
        // </summary>
        public static string No_Videos
        {
            get
            {
                return ResourceManager.GetString("No Videos", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to No Data Found.
        // </summary>
        public static string noSearch
        {
            get
            {
                return ResourceManager.GetString("noSearch", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Options.
        // </summary>
        public static string Options
        {
            get
            {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to our clients.
        // </summary>
        public static string our_clients
        {
            get
            {
                return ResourceManager.GetString("our clients", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Package Overview.
        // </summary>
        public static string Package_Overview
        {
            get
            {
                return ResourceManager.GetString("Package Overview", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Packages.
        // </summary>
        public static string Packages
        {
            get
            {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to PACKAGING SOLUTIONS.
        // </summary>
        public static string PACKAGING_SOLUTIONS
        {
            get
            {
                return ResourceManager.GetString("PACKAGING SOLUTIONS", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Photo Gallery.
        // </summary>
        public static string Photo_Gallery
        {
            get
            {
                return ResourceManager.GetString("Photo Gallery", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to play video.
        // </summary>
        public static string play_video
        {
            get
            {
                return ResourceManager.GetString("play video", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Product Leaflets.
        // </summary>
        public static string Product_Leaflets
        {
            get
            {
                return ResourceManager.GetString("Product Leaflets", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Product Overview.
        // </summary>
        public static string Product_Overview
        {
            get
            {
                return ResourceManager.GetString("Product Overview", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to products.
        // </summary>
        public static string products
        {
            get
            {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Projects.
        // </summary>
        public static string Projects
        {
            get
            {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Read More.
        // </summary>
        public static string Read_More
        {
            get
            {
                return ResourceManager.GetString("Read More", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Search.
        // </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to SearchResult for.
        // </summary>
        public static string SearchResult
        {
            get
            {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Select country.
        // </summary>
        public static string Select_country
        {
            get
            {
                return ResourceManager.GetString("Select country", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to send.
        // </summary>
        public static string send
        {
            get
            {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Services.
        // </summary>
        public static string Services
        {
            get
            {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to show all.
        // </summary>
        public static string show_all
        {
            get
            {
                return ResourceManager.GetString("show all", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to show details.
        // </summary>
        public static string show_details
        {
            get
            {
                return ResourceManager.GetString("show details", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Show Photo.
        // </summary>
        public static string Show_Photo
        {
            get
            {
                return ResourceManager.GetString("Show Photo", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Show Video.
        // </summary>
        public static string Show_Video
        {
            get
            {
                return ResourceManager.GetString("Show Video", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to message sent successfully !.
        // </summary>
        public static string success
        {
            get
            {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Technical Specifications.
        // </summary>
        public static string Technical_Specifications
        {
            get
            {
                return ResourceManager.GetString("Technical Specifications", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Tool Overview.
        // </summary>
        public static string Tool_Overview
        {
            get
            {
                return ResourceManager.GetString("Tool Overview", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to tools and equipment.
        // </summary>
        public static string tools
        {
            get
            {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to touch.
        // </summary>
        public static string touch
        {
            get
            {
                return ResourceManager.GetString("touch", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Under One Year.
        // </summary>
        public static string Under_One_Year
        {
            get
            {
                return ResourceManager.GetString("Under One Year", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to useful links.
        // </summary>
        public static string useful_links
        {
            get
            {
                return ResourceManager.GetString("useful links", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Vacancies.
        // </summary>
        public static string Vacancies
        {
            get
            {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to Video Gallery.
        // </summary>
        public static string Video_Gallery
        {
            get
            {
                return ResourceManager.GetString("Video Gallery", resourceCulture);
            }
        }

        // <summary>
        //   Looks up a localized string similar to something wrong happened !.
        // </summary>
        public static string wrong
        {
            get
            {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
    }
}
